### ISSUE TITLE
[HL] GitLab 15.x Fails on Charts

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#132]
Everything completes successfully, but the front end URL is empty.

**Comment by mental-lab** [comment]
I need to read the release notes better :slightly_smiling_face: . GitLab changed the allowed ciphers in commit: [a8483c25](https://gitlab.com/gitlab-org/charts/gitlab/-/commit/a8483c25d642b1e74507c066b52c975ff8a2b0d8) for GitLab v15.0 - Helm Chart v6.0 

Release notes: https://docs.gitlab.com/charts/releases/6_0.html#summary-of-major-changes

Looks like current testing (chart v6.4.2) ciphers are not compatible with recommended AWS lb policy : ELBSecurityPolicy-2016-08.

We needed to add the below ciphers within the helm chart values to get things working:
```
nginx-ingress:
  controller:
    config:
      ssl-ciphers: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
```
