### ISSUE TITLE
Potential bug: Object storage KMS key ID

### ISSUE THREAD

**Issue by tlindsay42** [aws-quickstart/quickstart-eks-gitlab#142]
While poking around in the templates today, I stumbled across this: https://github.com/aws-quickstart/quickstart-eks-gitlab/blob/783219d3309591053deb37b1462c15c09ef225f5/templates/workload/gitlab-storage-template.yaml#L33

Seems like the condition should evaluate the `SSEAlgorithm` parameter value instead of `KMSKeyID`. Will dive deeper later.

```diff
Conditions:
-  UseKMS: !Equals [!Ref KMSKeyID, 'aws:kms']
+  UseKMS: !Equals [!Ref SSEAlgorithm, 'aws:kms']
```

**Comment by kolomied** [comment]
@tlindsay42 You are right. This is from the very early days of the QS when we created the templates to support both AES256 and KMS but KMS support was never exposed through the top-level parameters (it is always AES256 atm). Therefore, we've never stumbled upon this typo.

Here is the top-level parameter definition (note there is no KMS option):

```yaml
  ObjectStorageSSEAlgorithm:
    Type: String
    Description: |
      GitLab will be configured to use object storage for everything that is capable of using it (artifacts, packages, lfs, etc.).
      Encryption algorithm for GitLab object storage artifacts.
    AllowedValues: [ 'AES256' ]
    Default: AES256
```

We have #11 to track the effort of supporting KMS for the object storage.
